import Head from 'next/head'

export default function Home() {
  return (
    <div className="px-8 py-0">
      <Head>
        <title>Ledafilms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-full py-16 flex flex-col justify-center items-center">
        <h1 className="m-0 leading-[1.15] texti-7xl text-center text-5xl">
          Welcome to <code className="bg-#FAFAFA rounded p-3 font-['Courier'] text-rose-400">Ledafilms</code>
        </h1>

        <p className="text-center my-16 mx-0 text-2xl">
          This is the landing page
        </p>

      </main>

    </div>
  )
}

